// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://asbgkynqicvthbxkxiqo.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzYmdreW5xaWN2dGhieGt4aXFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk2NDE4MjQsImV4cCI6MjEwNTIxNzgyNH0.JQaQ5jZ6ejXiwuu1YO1SgAOGV8e_DtCilwdRmq7qdJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
